services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: llm-gateway-vllm
    # Port offset for direct access bypassing the gateway
    ports:
      - "18001:8000"

    environment:
      HF_TOKEN: ${HF_TOKEN}

    volumes:
      - ./data/hf_cache:/root/.cache/huggingface

    ipc: host

    command: >
      --model ${MODEL_NAME} --host 0.0.0.0 --port 8000 --api-key ${VLLM_API_KEY} --gpu-memory-utilization 0.9 --enforce-eager --max-model-len ${MAX_MODEL_LEN} --trust-remote-code

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  gateway:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    container_name: llm-gateway-api
    ports:
      - "18000:8000"
    environment:
      - VLLM_URL=http://vllm:8000
      - VLLM_API_KEY=${VLLM_API_KEY}
      - DEFAULT_MODEL=${MODEL_NAME}
    volumes:
      - ./app:/app
      - /home/ucluser/workspace/UCLab/2025/scenefun3d/data:/home/ucluser/workspace/UCLab/2025/scenefun3d/data:ro
    depends_on:
      - vllm
