services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: llm-gateway-vllm
    ports:
      - "18000:8000"

    environment:
      HF_TOKEN: ${HF_TOKEN}

    volumes:
      - ./data/hf_cache:/root/.cache/huggingface

    ipc: host

    command: >
      Qwen/Qwen3.5-9B --host 0.0.0.0 --port 8000 --api-key ${VLLM_API_KEY} --gpu-memory-utilization 0.9 --enforce-eager --max-model-len 8192

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
